### ISSUE TITLE
Setup on a Raspberry Pi 3

### ISSUE THREAD

**Issue by peterjutzeler** [trifle/twitterresearch#12] opened 2018-01-12 15:13 UTC
Dear everybody.

I visited a course at the university and came in contact with twitterresearch. Meanwhile I did some small analysis for the homework. For my master thesis I would like to collect all the tweets with  #nobillag and #probillag. In Switzerland there is an voting about national media support on March 4th. I wanted to collect everything until then and this is not possible with my laptop. That's why I bought a Raspberry Pi 3 for that.

Do you know, why the same script does not work on the rpi that works on the macbook pro? I have ipython, did the preparation of the workspace as you tell to do in the tutorial.

Thank you for your help!

Here you find the nobillag.py file: 
https://www.dropbox.com/s/mfenuty0rswpdly/nobillag.py?dl=0

![error_rpi_twitterressearch](https://user-images.githubusercontent.com/22746148/34881251-511b79b2-f7b3-11e7-9f33-6d7a772fb61e.jpg)

**Comment by Millesimus** [comment] 2018-01-13 08:38
Hey peterjutzeler,

Nice solution to do that with a Raspberry I like that. 👍 

Your error message reads that you are lacking a particular module so you should install the missing yaml-module:
`sudo apt-get install python3-yaml`
Most likely this will not have been the last missing module but hopefully you can proceed likewise. For further trouble with absent packages and more information you might consider [this link](https://www.raspberrypi.org/documentation/linux/software/python.md).

Hope I could help!

**Comment by trifle** [comment] 2018-01-15 09:31
@peterjutzeler using the pi is a great idea! In general, most software works without too much effort. As @Millesimus mentioned, you will need to install some basic packages. Depending on the way you install python packages, you might need some development tools.
The database library works without those, but is much faster if you have them, so I'd recommend installing the system packages:

`sudo apt install python3-dev build-essential python3-pip`

and then getting newer versions through pip:

`sudo pip3 install -U setuptools wheel pip`
`sudo pip3 install -U peewee pyyaml (ADD MORE PACKAGES TO INSTALL/UPDATE HERE)`

Let me know if you have any issue with that.

**Comment by trifle** [comment] 2018-01-15 09:32
PS, of course the pi will be limited by its hardware; collecting tweets should work fine but you might run into RAM limitations with complex analysis workflows.

**Comment by trifle** [comment] 2018-01-15 09:37
Closing this, but feel free to re-open if you have any additional issue.

**Closed as completed by trifle** 2018-01-15 09:37 UTC

**Comment by peterjutzeler** [comment] 2018-01-16 11:01
Dear Pascal Jürgens

Thank you very much. It's the small things that take the time if you are 
only a social science student and not an data analyst. With your help it 
was only easy and I recognoised, that it is possible to run the 
funtcions with python 2.7 on the raspberry. there all the packages seeem 
to be installed allready and it works with your .py documents. The only 
thing I struggle now is, that the programm stops to collect tweets 
without mentioning it. I see it, because the data rate isn't increasing 
anymore. Now I try only to run on research at the moment. I wanted to 
collect 4 events in 4 different terminals. maybe it is better to collect 
all keywords of the different events in one function and store it in the 
same json-file.

And you are right with the power of the rpi. Collecting only needs up to 
4 percent of what the computer is capable. I prepare the files on my 
laptop and let the fast computer also store the json-file into the 
database. the transfer via dropbox is very easy. I'll start a second 
mining with a second rpi this week. It's fun, and I learn a lot about 
computers.

Thank you for your work! The twitterressearch is a great tool!


Am 2018-01-15 10:31, schrieb Pascal Jürgens:

**Comment by trifle** [comment] 2018-01-16 13:54
Dear Peter,

That’s wonderful kind feedback, many thanks.

With regard to the stream stopping: remember that one set of credentials (tokens) can only be used for one stream at a time. If you want to collect multiple, you need to setup multiple instances of the scripts with separate sets of tokens.

If that’s not the root cause of the stalls, feel free to open a new issue.

Cheers, Pascal

Sent from my iPhone

On 16. Jan 2018, at 12:01, peterjutzeler <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Pascal Jürgens

Thank you very much. It's the small things that take the time if you are
only a social science student and not an data analyst. With your help it
was only easy and I recognoised, that it is possible to run the
funtcions with python 2.7 on the raspberry. there all the packages seeem
to be installed allready and it works with your .py documents. The only
thing I struggle now is, that the programm stops to collect tweets
without mentioning it. I see it, because the data rate isn't increasing
anymore. Now I try only to run on research at the moment. I wanted to
collect 4 events in 4 different terminals. maybe it is better to collect
all keywords of the different events in one function and store it in the
same json-file.

And you are right with the power of the rpi. Collecting only needs up to
4 percent of what the computer is capable. I prepare the files on my
laptop and let the fast computer also store the json-file into the
database. the transfer via dropbox is very easy. I'll start a second
mining with a second rpi this week. It's fun, and I learn a lot about
computers.

Thank you for your work! The twitterressearch is a great tool!


Am 2018-01-15 10:31, schrieb Pascal Jürgens:
